/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kbcquizmt;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import static kbcquizmt.manageAccountplayer.dataplayer;

/**
 *
 * @author ASUS
 */
public class manageAdminAccount extends javax.swing.JFrame {
     private static Connection conn;
      DefaultTableModel tb = new DefaultTableModel();
      private static int gender;
    /**
     * Creates new form adminAccount
     */
    public manageAdminAccount() {
        initComponents();
        setIcon();
        load();
    }
    public void clear(){
        namea.setText("");
        passworda.setText("");
        addressa.setText("");
        emaila.setText("");
        ((JTextField)birthdaya.getDateEditor().getUiComponent()).setText("");
        statusa.setText("");
        
    }
    public void load(){
        try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"+"databaseName=KBCQuizDatabase","sa","sunflower");
           int number;
           Vector row, column;
           column = new Vector();
           Statement st = conn.createStatement();
           ResultSet rs= st.executeQuery("select * from Admin");
           ResultSetMetaData metadata= rs.getMetaData();
           number = metadata.getColumnCount();
           for(int i = 1;i<=number;i++){
               column.add(metadata.getColumnName(i));
           }
           tb.setColumnIdentifiers(column);
           while(rs.next()){
               row = new Vector();
               for(int i=1;i<=number;i++){
                  row.addElement(rs.getString(i));
               }
               tb.addRow(row);
               dataadmin.setModel(tb);
           }
           dataadmin.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
               @Override
               public void valueChanged(ListSelectionEvent e) {
                   if(dataadmin.getSelectedRow()>=0){                    
                      namea.setText(dataadmin.getValueAt(dataadmin.getSelectedRow(), 0)+ "");
                      passworda.setText(dataadmin.getValueAt(dataadmin.getSelectedRow(), 1)+ "");
                       addressa.setText(dataadmin.getValueAt(dataadmin.getSelectedRow(), 3)+ "");
                     emaila.setText(dataadmin.getValueAt(dataadmin.getSelectedRow(), 4)+ "");  
                    ((JTextField)birthdaya.getDateEditor().getUiComponent()).setText(dataadmin.getValueAt(dataadmin.getSelectedRow(), 5)+ "");
                     statusa.setText(dataadmin.getValueAt(dataadmin.getSelectedRow(), 6)+ "");

                      
                   }
               }
           });
            
                
             
                
                
       }
       catch(Exception e){
           System.out.println(e.getMessage());
       }
    }
                
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        inserta = new javax.swing.JButton();
        menua = new javax.swing.JButton();
        updatea = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataadmin = new javax.swing.JTable();
        namea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        femalea = new javax.swing.JRadioButton();
        malea = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        addressa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emaila = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        statusa = new javax.swing.JTextField();
        birthdaya = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        passworda = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KBC Quiz");
        setAlwaysOnTop(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(226,240,240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inserta.setBackground(new java.awt.Color(153, 255, 153));
        inserta.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        inserta.setText("Insert");
        inserta.setBorder(null);
        inserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaActionPerformed(evt);
            }
        });
        jPanel2.add(inserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, 25));

        menua.setBackground(new java.awt.Color(153, 255, 153));
        menua.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        menua.setText("Menu");
        menua.setBorder(null);
        menua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuaActionPerformed(evt);
            }
        });
        jPanel2.add(menua, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 100, 25));

        updatea.setBackground(new java.awt.Color(153, 255, 153));
        updatea.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        updatea.setText("Update");
        updatea.setBorder(null);
        updatea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateaActionPerformed(evt);
            }
        });
        jPanel2.add(updatea, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, 25));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel3.setText("Adminname");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        dataadmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dataadmin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dataadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataadmin.setFocusable(false);
        dataadmin.setIntercellSpacing(new java.awt.Dimension(2, 2));
        dataadmin.setSelectionBackground(new java.awt.Color(226,240,240));
        dataadmin.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(dataadmin);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 239, 950, 300));

        namea.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        namea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(namea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 205, 25));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setText("Gender");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        buttonGroup1.add(femalea);
        femalea.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        femalea.setText("Female");
        femalea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleaMouseClicked(evt);
            }
        });
        jPanel2.add(femalea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        buttonGroup1.add(malea);
        malea.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        malea.setText("Male");
        malea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleaMouseClicked(evt);
            }
        });
        jPanel2.add(malea, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setText("Address");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        addressa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addressa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(addressa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 205, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setText("Email");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        emaila.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emaila.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(emaila, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 205, 25));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setText("Birthday");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel9.setText("Status");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        statusa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        statusa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        statusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusaActionPerformed(evt);
            }
        });
        jPanel2.add(statusa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 205, -1));

        birthdaya.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        birthdaya.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(birthdaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 205, 28));

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton4.setText("Delete");
        jButton4.setBorder(null);
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 100, 25));

        jPanel3.setBackground(new java.awt.Color(255,255,255,150));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel10.setText("Admin Account List");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 950, 40));

        jPanel4.setBackground(new java.awt.Color(255,255,255,150));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel2.setText("Manage Admin Account");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(387, 387, 387))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        passworda.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passworda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(passworda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 205, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 950, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\sky1.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaActionPerformed
        String name1 = namea.getText();
        String PATTERN ="^[a-zA-Z]{1,60}$";
        Pattern pt = Pattern.compile(PATTERN);
        Matcher match=pt.matcher(namea.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(this, "Please enter your name only contains character!");
        }
        String PATTERN1 ="((?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,50})";
        Pattern pt1 =Pattern.compile(PATTERN1);
        Matcher match1=pt1.matcher(passworda.getText());
        if(!match1.matches()){
            JOptionPane.showMessageDialog(this, "Password must contain at least one digit, one lowercase,one uppercase character, length from 8 to 50 characters!");
        }
        String address1 = addressa.getText();
        if(address1.equals("")){
           JOptionPane.showMessageDialog(this, "Please enter your address!");
        }
        String PATTERN2 ="^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        Pattern pt2 =Pattern.compile(PATTERN2);
        Matcher match2 = pt2.matcher(emaila.getText());
        if(!match2.matches()){
            JOptionPane.showMessageDialog(this, "Email invalid!\nExample: parkjyeon@gmail.com");
        }
        String birthday1= ((JTextField)birthdaya.getDateEditor().getUiComponent()).getText();
        if(birthday1.equals("")){
           JOptionPane.showMessageDialog(this, "Please enter your birthday!");
        }
        if(match.matches()&&match1.matches()&&!address1.equals("")&&match2.matches()&&!birthday1.equals("")){
        
         try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"+"databaseName=KBCQuizDatabase","sa","sunflower");
              String check = "select * from Admin where Adminname=?";
              PreparedStatement pst1 = conn.prepareStatement(check);
              pst1.setString(1,namea.getText());
              ResultSet rs = pst1.executeQuery();
              if(rs.next()){
                  JOptionPane.showMessageDialog(this, "Name has already used!");
              }
              
              else{
              PreparedStatement pst = conn.prepareStatement("insert into Admin(Adminname,Password,Gender,Address,Email,Birthday,Status) values(?,?,?,?,?,?,?)");
              pst.setString(1,namea.getText());
              pst.setString(2,passworda.getText());
              pst.setInt(3, gender); 
              pst.setString(4,addressa.getText());  
              pst.setString(5,(emaila.getText()));         
                      
              pst.setString(6,((JTextField)birthdaya.getDateEditor().getUiComponent()).getText());
             
              pst.setString(7, statusa.getText());
              int result = pst.executeUpdate();
              if(result>0){
                  JOptionPane.showMessageDialog(this, "Insert successfully!");
                  tb.setRowCount(0);
                  load();
                  clear();
              }
              else{
                  JOptionPane.showMessageDialog(this, "Insert unsucessufuly!");
              }
         }
              clear();
         }
         catch(Exception e){
             System.out.println(e.getMessage());
         }
        }
    }//GEN-LAST:event_insertaActionPerformed

    private void statusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusaActionPerformed
        
    }//GEN-LAST:event_statusaActionPerformed

    private void femaleaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleaMouseClicked
          gender =1;
    }//GEN-LAST:event_femaleaMouseClicked

    private void maleaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleaMouseClicked
        gender =0;
    }//GEN-LAST:event_maleaMouseClicked

    private void updateaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateaActionPerformed
         String name1 = namea.getText();
        String PATTERN ="^[a-zA-Z]{1,60}$";
        Pattern pt = Pattern.compile(PATTERN);
        Matcher match=pt.matcher(namea.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(this, "Please enter your name only contains character!");
        }
        String PATTERN1 ="((?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,50})";
        Pattern pt1 =Pattern.compile(PATTERN1);
        Matcher match1=pt1.matcher(passworda.getText());
        if(!match1.matches()){
            JOptionPane.showMessageDialog(this, "Password must contain at least one digit, one lowercase,one uppercase character, length from 8 to 50 characters!");
        }
        String address1 = addressa.getText();
        if(address1.equals("")){
           JOptionPane.showMessageDialog(this, "Please enter your address!");
        }
        String PATTERN2 ="^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        Pattern pt2 =Pattern.compile(PATTERN2);
        Matcher match2 = pt2.matcher(emaila.getText());
        if(!match2.matches()){
            JOptionPane.showMessageDialog(this, "Email invalid!\nExample: parkjyeon@gmail.com");
        }
        String birthday1= ((JTextField)birthdaya.getDateEditor().getUiComponent()).getText();
        if(birthday1.equals("")){
           JOptionPane.showMessageDialog(this, "Please enter your birthday!");
        }
        if(match.matches()&&match1.matches()&&!address1.equals("")&&match2.matches()&&!birthday1.equals("")){

        try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"+"databaseName=KBCQuizDatabase","sa","sunflower");
           

           String update= "update Admin set Password=?, Gender=?,Address=?,Email=?,Birthday=?,Status=? where Adminname=?";
             PreparedStatement pst = conn.prepareStatement(update);
              pst.setString(7, namea.getText());
              pst.setString(1,passworda.getText());
              pst.setInt(2, gender); 
              pst.setString(3,addressa.getText());  
              pst.setString(4,(emaila.getText()));         
                      
              pst.setString(5,((JTextField)birthdaya.getDateEditor().getUiComponent()).getText());
              pst.setString(6, statusa.getText());
              pst.executeUpdate();
              JOptionPane.showMessageDialog(this, "update Successfully");
              tb.setRowCount(0);
              load();
              clear();
        }
         
    
         catch(Exception e){
             System.out.println(e.getMessage());
         }
        }
         
    }//GEN-LAST:event_updateaActionPerformed

    private void menuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuaActionPerformed
        new menuAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoAdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoAdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoAdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoAdminAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageAdminAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressa;
    private com.toedter.calendar.JDateChooser birthdaya;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTable dataadmin;
    private javax.swing.JTextField emaila;
    private javax.swing.JRadioButton femalea;
    private javax.swing.JButton inserta;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton malea;
    private javax.swing.JButton menua;
    private javax.swing.JTextField namea;
    private javax.swing.JPasswordField passworda;
    private javax.swing.JTextField statusa;
    private javax.swing.JButton updatea;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logokbcquiz2.png")));
    }
}
