/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kbcquizmt;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class menuForm extends javax.swing.JFrame {
    private static Connection conn;
    /**
     * Creates new form menuForm
     */
    public menuForm() {
        initComponents();
        setIcon();
        showName();
    }
    public void showName(){
        try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"+"databaseName=KBCQuizDatabase","sa","sunflower");
            String show = "select * from Player where Playername=?";
             PreparedStatement pst = conn.prepareStatement(show);
             pst.setString(1,LoginForm.namelogin.getText());
             ResultSet rs = pst.executeQuery();
             if(rs.next()){
                 String displayInfo = "select * from Player where Playername=? ";
                 PreparedStatement pst1 = conn.prepareStatement(displayInfo);
                 pst1.setString(1, LoginForm.namelogin.getText());
                 ResultSet result = pst1.executeQuery();
                 if(result.next()){
                     String namep = result.getString(1);                    
                     hiname.setText(namep);                    
                 }     
             }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pgmenu = new javax.swing.JPanel();
        playgame = new javax.swing.JLabel();
        gamerule = new javax.swing.JPanel();
        rule = new javax.swing.JLabel();
        prizemoney = new javax.swing.JPanel();
        money = new javax.swing.JLabel();
        viewaccount = new javax.swing.JPanel();
        vaccount = new javax.swing.JLabel();
        updateaccount = new javax.swing.JPanel();
        upaccount = new javax.swing.JLabel();
        changepassword = new javax.swing.JPanel();
        cpassword = new javax.swing.JLabel();
        logoutp = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hiname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        playnow = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - KBC Quiz");
        setAlwaysOnTop(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pgmenu.setBackground(new java.awt.Color(255, 255, 255));
        pgmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pgmenuMouseEntered(evt);
            }
        });

        playgame.setBackground(new java.awt.Color(255, 255, 255));
        playgame.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        playgame.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\playgameicon.png")); // NOI18N
        playgame.setText("Play Game");
        playgame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playgameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playgameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playgameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pgmenuLayout = new javax.swing.GroupLayout(pgmenu);
        pgmenu.setLayout(pgmenuLayout);
        pgmenuLayout.setHorizontalGroup(
            pgmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playgame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pgmenuLayout.setVerticalGroup(
            pgmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playgame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(pgmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        gamerule.setBackground(new java.awt.Color(255, 255, 255));

        rule.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        rule.setText("Game Rule");
        rule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ruleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ruleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ruleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout gameruleLayout = new javax.swing.GroupLayout(gamerule);
        gamerule.setLayout(gameruleLayout);
        gameruleLayout.setHorizontalGroup(
            gameruleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameruleLayout.createSequentialGroup()
                .addComponent(rule, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gameruleLayout.setVerticalGroup(
            gameruleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameruleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rule, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(gamerule, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 100, 30));

        prizemoney.setBackground(new java.awt.Color(255, 255, 255));

        money.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        money.setText("Prize Money");
        money.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        money.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moneyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moneyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moneyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout prizemoneyLayout = new javax.swing.GroupLayout(prizemoney);
        prizemoney.setLayout(prizemoneyLayout);
        prizemoneyLayout.setHorizontalGroup(
            prizemoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(money, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        prizemoneyLayout.setVerticalGroup(
            prizemoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(money, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(prizemoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 110, 30));

        viewaccount.setBackground(new java.awt.Color(255, 255, 255));

        vaccount.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        vaccount.setText("View Account");
        vaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vaccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vaccountMouseExited(evt);
            }
        });

        javax.swing.GroupLayout viewaccountLayout = new javax.swing.GroupLayout(viewaccount);
        viewaccount.setLayout(viewaccountLayout);
        viewaccountLayout.setHorizontalGroup(
            viewaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaccount, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        viewaccountLayout.setVerticalGroup(
            viewaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaccount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(viewaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 120, 30));

        updateaccount.setBackground(new java.awt.Color(255, 255, 255));

        upaccount.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        upaccount.setText("Update Account");
        upaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upaccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upaccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upaccountMouseExited(evt);
            }
        });

        javax.swing.GroupLayout updateaccountLayout = new javax.swing.GroupLayout(updateaccount);
        updateaccount.setLayout(updateaccountLayout);
        updateaccountLayout.setHorizontalGroup(
            updateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updateaccountLayout.setVerticalGroup(
            updateaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upaccount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(updateaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 30));

        changepassword.setBackground(new java.awt.Color(255, 255, 255));

        cpassword.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cpassword.setText("Change Password");
        cpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cpasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cpasswordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout changepasswordLayout = new javax.swing.GroupLayout(changepassword);
        changepassword.setLayout(changepasswordLayout);
        changepasswordLayout.setHorizontalGroup(
            changepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        changepasswordLayout.setVerticalGroup(
            changepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(changepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, 30));

        logoutp.setBackground(new java.awt.Color(255, 255, 255));

        logout.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        logout.setText("  Log Out");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logoutpLayout = new javax.swing.GroupLayout(logoutp);
        logoutp.setLayout(logoutpLayout);
        logoutpLayout.setHorizontalGroup(
            logoutpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        logoutpLayout.setVerticalGroup(
            logoutpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(logoutp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 40));

        jPanel3.setBackground(new java.awt.Color(226,240,240));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255,255,255,100));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setText("Welcome ");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 30));

        hiname.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jPanel4.add(hiname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 220, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel4.setText(" To ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 50, 30));

        playnow.setBackground(new java.awt.Color(153, 255, 153));
        playnow.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        playnow.setText("Play Now");
        playnow.setBorder(null);
        playnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playnowActionPerformed(evt);
            }
        });
        jPanel4.add(playnow, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\logokbcquiz.png")); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 300, 190));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 530, 360));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\sky1.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1010, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pgmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pgmenuMouseEntered
        
    }//GEN-LAST:event_pgmenuMouseEntered

    private void playgameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playgameMouseEntered
        setColor(pgmenu);
    }//GEN-LAST:event_playgameMouseEntered

    private void playgameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playgameMouseExited
        resetColor(pgmenu);
    }//GEN-LAST:event_playgameMouseExited

    private void ruleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ruleMouseEntered
        // TODO add your handling code here:
       setColor(gamerule);
    }//GEN-LAST:event_ruleMouseEntered

    private void ruleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ruleMouseExited
        resetColor(gamerule);
    }//GEN-LAST:event_ruleMouseExited

    private void moneyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyMouseEntered
        setColor(prizemoney);
    }//GEN-LAST:event_moneyMouseEntered

    private void moneyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyMouseExited
       resetColor(prizemoney);
    }//GEN-LAST:event_moneyMouseExited

    private void vaccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccountMouseEntered
        setColor(viewaccount);
    }//GEN-LAST:event_vaccountMouseEntered

    private void vaccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccountMouseExited
       resetColor(viewaccount);
    }//GEN-LAST:event_vaccountMouseExited

    private void upaccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upaccountMouseEntered
        setColor(updateaccount);
    }//GEN-LAST:event_upaccountMouseEntered

    private void upaccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upaccountMouseExited
        resetColor(updateaccount);
    }//GEN-LAST:event_upaccountMouseExited

    private void cpasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpasswordMouseEntered
        setColor(changepassword);
    }//GEN-LAST:event_cpasswordMouseEntered

    private void cpasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpasswordMouseExited
       resetColor(changepassword);
    }//GEN-LAST:event_cpasswordMouseExited

    private void ruleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ruleMouseClicked
        new gameRule().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ruleMouseClicked

    private void moneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyMouseClicked
        new prizeMoney().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_moneyMouseClicked

    private void vaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaccountMouseClicked
        new FormAccount().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_vaccountMouseClicked

    private void upaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upaccountMouseClicked
        
    }//GEN-LAST:event_upaccountMouseClicked

    private void cpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpasswordMouseClicked
        new changePassword().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cpasswordMouseClicked

    private void playgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playgameMouseClicked
        new ChooseQuestion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_playgameMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new welcomeForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
       setColor(logoutp);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
         resetColor(logoutp);
    }//GEN-LAST:event_logoutMouseExited

    private void playnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playnowActionPerformed
        new ChooseQuestion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_playnowActionPerformed
    public void setColor(JPanel c){
        c.setBackground(new Color(204,255,204));
    }
    public void resetColor(JPanel c){
        c.setBackground(Color.white);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel changepassword;
    private javax.swing.JLabel cpassword;
    private javax.swing.JPanel gamerule;
    public static javax.swing.JLabel hiname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel logoutp;
    private javax.swing.JLabel money;
    private javax.swing.JPanel pgmenu;
    private javax.swing.JLabel playgame;
    private javax.swing.JButton playnow;
    private javax.swing.JPanel prizemoney;
    private javax.swing.JLabel rule;
    private javax.swing.JLabel upaccount;
    private javax.swing.JPanel updateaccount;
    private javax.swing.JLabel vaccount;
    private javax.swing.JPanel viewaccount;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logokbcquiz2.png")));
    }
}
