/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kbcquizmt;

import java.awt.Toolkit;

/**
 *
 * @author ASUS
 */
public class prizeMoney extends javax.swing.JFrame {

    /**
     * Creates new form prizeMoney
     */
    public prizeMoney() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTable1);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\prizemoney.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\prizemoney.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\prizemoney.png")); // NOI18N

        jLabel7.setText("jLabel7");

        jPanel4.setBackground(new java.awt.Color(255,255,255,150));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255,255,255,150
        ));
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\jiyeon2.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\prizemoney.png")); // NOI18N

        jLabel34.setText("jLabel34");

        jLabel35.setText("jLabel35");

        jLabel36.setText("jLabel36");

        jLabel37.setText("jLabel37");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setText("No.Question");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setText("Right Answer");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel12.setText("Wrong Answer");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel13.setText("Missed Answer");

        jLabel14.setText("jLabel14");

        jLabel15.setText("jLabel15");

        jLabel16.setText("jLabel16");

        jLabel17.setText("jLabel17");

        jLabel18.setText("jLabel18");

        jLabel19.setText("jLabel19");

        jLabel20.setText("jLabel20");

        jLabel21.setText("jLabel21");

        jLabel22.setText("jLabel22");

        jLabel23.setText("jLabel23");

        jLabel24.setText("jLabel24");

        jLabel25.setText("jLabel25");

        jLabel26.setText("jLabel26");

        jLabel27.setText("jLabel27");

        jLabel28.setText("jLabel28");

        jLabel29.setText("jLabel29");

        jLabel30.setText("jLabel30");

        jLabel31.setText("jLabel31");

        jLabel32.setText("jLabel32");

        jLabel33.setText("jLabel33");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(jLabel23)
                    .addComponent(jLabel14)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel13)))
                .addGap(40, 40, 40))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(2, 2, 2)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addComponent(jLabel16)
                .addGap(7, 7, 7)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(1, 1, 1)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addGap(30, 30, 30)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );

        jLabel58.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel58.setText("20");

        jLabel57.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel57.setText("19");

        jLabel56.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel56.setText("18");

        jLabel55.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel55.setText("17");

        jLabel53.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel53.setText("15");

        jLabel54.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel54.setText("16");

        jLabel52.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel52.setText("14");

        jLabel75.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel75.setText("$10,000");

        jLabel76.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel76.setText("$12,000");

        jLabel77.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel77.setText("$14,000");

        jLabel79.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel79.setText("$20,000");

        jLabel78.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel78.setText("$18,000");

        jLabel80.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel80.setText("$50,000");

        jLabel81.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel81.setText("$1,000,000");

        jLabel101.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel101.setText("$20,000");

        jLabel99.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel99.setText("$5,000");

        jLabel98.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel98.setText("$4,000");

        jLabel100.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel100.setText("$10,000");

        jLabel97.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel97.setText("$3,000");

        jLabel96.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel96.setText("$3,000");

        jLabel95.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel95.setText("$2,000");

        jLabel115.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel115.setText("$2,000");

        jLabel116.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel116.setText("$3,000");

        jLabel117.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel117.setText("$3,000");

        jLabel118.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel118.setText("$4,000");

        jLabel119.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel119.setText("$5,000");

        jLabel120.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel120.setText("$10,000");

        jLabel121.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel121.setText("$20,000");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel3.setText("Prize Money Format");

        label1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label1.setText("Walk away value");

        jLabel122.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel122.setText("Missed Answer");

        jLabel123.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel123.setText("Missed Answer");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KBC Quiz");
        setAlwaysOnTop(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255,255,255,100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255,255,255,150));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255,255,255,150));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel38.setText("No.Question");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel39.setText("1");
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel40.setText("2");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel41.setText("3");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel42.setText("4");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel43.setText("5");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel44.setText("6");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel45.setText("7");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel46.setText("8");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel47.setText("9");
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel48.setText("10");
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel49.setText("11");
        jPanel8.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel50.setText("12");
        jPanel8.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel51.setText("13");
        jPanel8.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel59.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel59.setText("Right Answer");
        jPanel8.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel60.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel60.setText("Wrong Answer");
        jPanel8.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jLabel61.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel61.setText("Missed Answer");
        jPanel8.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 140, -1));

        jLabel62.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel62.setText("$50");
        jPanel8.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel63.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel63.setText("$100");
        jPanel8.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel64.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel64.setText("$200");
        jPanel8.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel65.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel65.setText("$400");
        jPanel8.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel66.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel66.setText("$800");
        jPanel8.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel67.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel67.setText("$1,600");
        jPanel8.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel68.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel68.setText("$3,200");
        jPanel8.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jLabel69.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel69.setText("$6,400");
        jPanel8.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel70.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel70.setText("$12,500");
        jPanel8.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel71.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel71.setText("$25,000");
        jPanel8.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel72.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel72.setText("$50,000");
        jPanel8.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel73.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel73.setText("$1,000,000");
        jPanel8.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jLabel74.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel74.setText("$5,000,000");
        jPanel8.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jLabel82.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel82.setText("$0");
        jPanel8.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel83.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel83.setText("$0");
        jPanel8.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel84.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel84.setText("$100");
        jPanel8.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel85.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel85.setText("$100");
        jPanel8.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel86.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel86.setText("$100");
        jPanel8.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel87.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel87.setText("$100");
        jPanel8.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jLabel88.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel88.setText("$100");
        jPanel8.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jLabel89.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel89.setText("$3,200");
        jPanel8.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jLabel90.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel90.setText("$3,200");
        jPanel8.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jLabel91.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel91.setText("$3,200");
        jPanel8.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel92.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel92.setText("$3,200");
        jPanel8.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        jLabel93.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel93.setText("$3,200");
        jPanel8.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jLabel94.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel94.setText("$3,200");
        jPanel8.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        jLabel102.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel102.setText("$0");
        jPanel8.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel103.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel103.setText("$50");
        jPanel8.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jLabel104.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel104.setText("$100");
        jPanel8.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel105.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel105.setText("$200");
        jPanel8.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jLabel106.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel106.setText("$400");
        jPanel8.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel107.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel107.setText("$800");
        jPanel8.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel108.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel108.setText("$1,600");
        jPanel8.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel109.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel109.setText("$3,200");
        jPanel8.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel110.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel110.setText("$6,400");
        jPanel8.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel111.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel111.setText("$12,500");
        jPanel8.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jLabel112.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel112.setText("$25,000");
        jPanel8.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        jLabel113.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel113.setText("$1,000,000");
        jPanel8.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel114.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel114.setText("$50,000");
        jPanel8.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jLabel124.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel124.setText("Walk away ");
        jPanel8.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabel125.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel125.setText("$0");
        jPanel8.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jLabel126.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel126.setText("Prize money format");
        jPanel8.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel127.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel127.setText("$50");
        jPanel8.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        jLabel128.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel128.setText("$100");
        jPanel8.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jLabel129.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel129.setText("$100");
        jPanel8.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel130.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel130.setText("$300");
        jPanel8.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        jLabel131.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel131.setText("$700");
        jPanel8.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel132.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel132.setText("$1,500");
        jPanel8.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jLabel133.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel133.setText("$3,200");
        jPanel8.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jLabel134.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel134.setText("$3,200");
        jPanel8.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jLabel135.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel135.setText("$9,300");
        jPanel8.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        jLabel136.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel136.setText("$21,800");
        jPanel8.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        jLabel137.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel137.setText("$46,800");
        jPanel8.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        jLabel138.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel138.setText("$96,800");
        jPanel8.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton1.setText("Got it");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 100, 35));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 520));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\jiyeon4.1.jpg")); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 520));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 750, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 750, 550));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 750, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\sky1.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new menuForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prizeMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prizeMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prizeMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prizeMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prizeMoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logokbcquiz2.png")));
    }
}
