/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kbcquizmt;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.regex.*;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static kbcquizmt.register.conn;


/**
 *
 * @author ASUS
 */
public class register extends javax.swing.JFrame{
           public static Connection conn;
          
        
    /**
     * Creates new form test1
     */
    public register() {
       
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        textrepassword = new javax.swing.JPasswordField("iconeye.png");
        jPanel6 = new javax.swing.JPanel();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textpassword = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        textaddress = new javax.swing.JTextField();
        textemail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        gologin = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        register = new javax.swing.JButton();
        birthdaytext = new com.toedter.calendar.JDateChooser();
        errrepass = new javax.swing.JLabel();
        errpass = new javax.swing.JLabel();
        erremail = new javax.swing.JLabel();
        errname = new javax.swing.JLabel();
        erraddress = new javax.swing.JLabel();
        errpass2 = new javax.swing.JLabel();
        erremail2 = new javax.swing.JLabel();
        repassword = new javax.swing.JPasswordField();
        checkshow = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel11.setText("jLabel11");

        jPasswordField2.setText("jPasswordField2");
        jPasswordField2.getAccessibleContext().setAccessibleName("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\calendaricon.png")); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\calendaricon.png")); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\iconeye.png")); // NOI18N

        textrepassword.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        textrepassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textrepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textrepasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KBC Quiz");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(226, 240, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        name.setText("Name");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setText("Re-Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setText("Gender");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setText("Birthday");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setText("Address");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        textname.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        textname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });
        textname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textnameKeyReleased(evt);
            }
        });
        jPanel2.add(textname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 380, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        textpassword.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        textpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textpassword.setPreferredSize(new java.awt.Dimension(156, 39));
        textpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textpasswordKeyReleased(evt);
            }
        });
        jPanel2.add(textpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 380, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 40, -1));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        textaddress.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        textaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textaddressKeyReleased(evt);
            }
        });
        jPanel2.add(textaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 380, 30));

        textemail.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        textemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textemailActionPerformed(evt);
            }
        });
        textemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textemailKeyReleased(evt);
            }
        });
        jPanel2.add(textemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 380, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel21.setText("Already have account?");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        gologin.setBackground(new java.awt.Color(0, 0, 0));
        gologin.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        gologin.setForeground(new java.awt.Color(0, 204, 204));
        gologin.setText("Login");
        gologin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gologin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gologinMouseClicked(evt);
            }
        });
        jPanel2.add(gologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        female.setText("Female");
        female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        male.setText("Male");
        male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        register.setBackground(new java.awt.Color(153, 255, 153));
        register.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        register.setText("Register");
        register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel2.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 100, 35));

        birthdaytext.setToolTipText("");
        birthdaytext.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        birthdaytext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                birthdaytextKeyReleased(evt);
            }
        });
        jPanel2.add(birthdaytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 380, 30));

        errrepass.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        errrepass.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(errrepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 400, 17));

        errpass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        errpass.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(errpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 530, 17));

        erremail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        erremail.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(erremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 380, 17));

        errname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        errname.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(errname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 380, 20));

        erraddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        erraddress.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(erraddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 380, 17));

        errpass2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        errpass2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(errpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 380, 17));

        erremail2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        erremail2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(erremail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 390, 17));

        repassword.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        repassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        repassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repasswordActionPerformed(evt);
            }
        });
        repassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                repasswordKeyReleased(evt);
            }
        });
        jPanel2.add(repassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 380, 30));

        checkshow.setBackground(new java.awt.Color(255, 255, 255));
        checkshow.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        checkshow.setText("Show password");
        checkshow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkshowActionPerformed(evt);
            }
        });
        jPanel2.add(checkshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 160, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel3.setText("Register");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel3)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        reset.setBackground(new java.awt.Color(153, 255, 153));
        reset.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 100, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 590, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Imageforproject\\sky1.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnameActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void textrepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textrepasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textrepasswordActionPerformed

    private void textemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textemailActionPerformed

    private void textnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnameKeyReleased
        String PATTERN ="^[a-zA-Z]{1,60}$";
        Pattern pt = Pattern.compile(PATTERN);
        Matcher match=pt.matcher(textname.getText());
        if(!match.matches()){
            errname.setText("Please enter your name only contains character!");
        }
        else{
            errname.setText(null);
        }
        
    }//GEN-LAST:event_textnameKeyReleased

    private void textpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textpasswordKeyReleased
        // TODO add your handling code here:
        String PATTERN ="((?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,50})";
        Pattern pt =Pattern.compile(PATTERN);
        Matcher match=pt.matcher(textpassword.getText());
        if(!match.matches()){
            errpass.setText("Password must contain at least 1 digit, 1 lowercase,");
            errpass2.setText("1 uppercase character, length from 8 to 50 characters!");
        }
        else{
            errpass.setText(null);
            errpass2.setText(null);
        }
    }//GEN-LAST:event_textpasswordKeyReleased

    private void textaddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textaddressKeyReleased
       String address = textaddress.getText();
       if(address.equals("")){
           erraddress.setText("Please enter your address!");
       }
       else{
           erraddress.setText(null);
       }
    }//GEN-LAST:event_textaddressKeyReleased

    private void textemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textemailKeyReleased
        String PATTERN ="^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        Pattern pt =Pattern.compile(PATTERN);
        Matcher match = pt.matcher(textemail.getText());
        if(!match.matches()){
            erremail.setText("Email invalid!");
            erremail2.setText("Example: parkjyeon@gmail.com");
        }
        else{
            erremail.setText(null);
            erremail2.setText(null);
        }
    }//GEN-LAST:event_textemailKeyReleased
  
    
    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String name = textname.getText();
        String PATTERN ="^[a-zA-Z]{1,60}$";
        Pattern pt = Pattern.compile(PATTERN);
        Matcher match=pt.matcher(textname.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(this, "Please enter your name only contains character!");
        }
        String PATTERN1 ="((?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,50})";
        Pattern pt1 =Pattern.compile(PATTERN1);
        Matcher match1=pt1.matcher(textpassword.getText());
        if(!match1.matches()){
            JOptionPane.showMessageDialog(this, "Password must contain at least one digit, one lowercase,one uppercase character, length from 8 to 50 characters!");
        }
        String address = textaddress.getText();
        if(address.equals("")){
           JOptionPane.showMessageDialog(this, "Please enter your address!");
        }
        String PATTERN2 ="^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        Pattern pt2 =Pattern.compile(PATTERN2);
        Matcher match2 = pt2.matcher(textemail.getText());
        if(!match2.matches()){
            JOptionPane.showMessageDialog(this, "Email invalid!\nExample: parkjyeon@gmail.com");
        }
        String birthday1= ((JTextField)birthdaytext.getDateEditor().getUiComponent()).getText();
        if(birthday1.equals("")){
           JOptionPane.showMessageDialog(this, "Please enter your birthday!");
        }
         if(!repassword.getText().equals(textpassword.getText())){
             JOptionPane.showMessageDialog(this, "Password doesn't match!");
         }
         if(match.matches()&&match1.matches()&&!address.equals("")&&match2.matches()&&!birthday1.equals("")&&repassword.getText().equals(textpassword.getText())){
           try{           
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
              conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"+"databaseName=KBCQuizDatabase","sa","sunflower");
               
              String check = "select * from Player where Playername=?";
              PreparedStatement pst1 = conn.prepareStatement(check);
              pst1.setString(1,textname.getText());
              ResultSet rs = pst1.executeQuery();
             if(rs.next()){
                  JOptionPane.showMessageDialog(this, "This name has already used!");
              }
             else{
              String insert = "insert into Player(Playername,Password,Gender,Address,Email,Birthday) values(?,?,?,?,?,?)";
              PreparedStatement pst = conn.prepareStatement(insert);
              pst.setString(1,textname.getText());
              pst.setString(2,textpassword.getText());
              pst.setString(3, gender);
              pst.setString(4,textaddress.getText());
              pst.setString(5,textemail.getText());
              pst.setString(6,((JTextField)birthdaytext.getDateEditor().getUiComponent()).getText());
              int result = pst.executeUpdate();
             
              
            if(result>0){
               JOptionPane.showMessageDialog(this, "You have registered successfully!");
               new LoginForm().setVisible(true);
               this.setVisible(false);  
                  }
             }
           }
            catch(Exception ex){
                 System.out.println(ex.getMessage());
            }
            }
         
         
    }//GEN-LAST:event_registerActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        gender = "Female";
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        gender = "Male";
    }//GEN-LAST:event_maleActionPerformed

    private void repasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repasswordKeyReleased
        if(!repassword.getText().equals(textpassword.getText())){
            errrepass.setText("Password doesn't match!");
        }
        else{
            errrepass.setText(null);
        }
    }//GEN-LAST:event_repasswordKeyReleased

    private void repasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repasswordActionPerformed

    private void birthdaytextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_birthdaytextKeyReleased
        
     
    }//GEN-LAST:event_birthdaytextKeyReleased
    
    private void checkshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkshowActionPerformed
       if(checkshow.isSelected()){
           repassword.setEchoChar((char)0);
       }
       else{
           repassword.setEchoChar('*');
       }
    }//GEN-LAST:event_checkshowActionPerformed

    private void gologinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gologinMouseClicked
        new LoginForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gologinMouseClicked
    public void clear(){
        textname.setText("");
        textpassword.setText("");
        repassword.setText("");
        textaddress.setText("");
        textemail.setText("");
        ((JTextField)birthdaytext.getDateEditor().getUiComponent()).setText("");
    }
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        clear();
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
   
    }

    private void setIconImage() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logokbcquiz2.png")));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser birthdaytext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox checkshow;
    private javax.swing.JLabel erraddress;
    private javax.swing.JLabel erremail;
    private javax.swing.JLabel erremail2;
    private javax.swing.JLabel errname;
    private javax.swing.JLabel errpass;
    private javax.swing.JLabel errpass2;
    private javax.swing.JLabel errrepass;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gologin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel name;
    private javax.swing.JButton register;
    private javax.swing.JPasswordField repassword;
    private javax.swing.JButton reset;
    private javax.swing.JTextField textaddress;
    private javax.swing.JTextField textemail;
    public static javax.swing.JTextField textname;
    private javax.swing.JPasswordField textpassword;
    private javax.swing.JPasswordField textrepassword;
    // End of variables declaration//GEN-END:variables
    private String gender;
    
}
